### ISSUE TITLE
msz_per_channel？

### ISSUE THREAD

**Issue by nightrain-vampire** [sdh0818/FreD#1]
Thanks for your work! Could you explain the  meaning of  the argument 'msz_per_channel' for me?

**Comment by sdh0818** [comment]
First of all, thank you for your interest.

"msz_per_channel" means the memory size (or budget size) per channel.

FreD selects informative frequency domain dimensions and utilizes them. In this case, the informative frequency domain dimensions are assumed to be the same for each channel. Therefore, in FreD, the budget size required to represent one synthetic instance can be expressed as (channel $\times$ msz_per_channel).

For example, let's assume ipc=1, msz_per_channel=64, and CIFAR-10. 
Then, the budget size of each class is (ipc $\times$ channel $\times$ height $\times$ width) = 1 $\times$ 3 $\times$ 32 $\times$ 32 = 3072. 
Since FreD represents one instance with a budget size of (channel $\times$ msz_per_channel) = 3 $\times$ 64 = 192, it can create a total of 3072/192=16 instances at the same budget size.
In the actual code, the formula is represented without the channel size since it disappears in the division operation.

If you have any further questions, please let me know.
